[package]
name = "koek-redact"
version = "0.1.0"
edition = "2021"
description = "Allows for redaction of values when outputting them to places where sensitive data is not permitted."
license = "MIT"
repository = "https://github.com/sandersaares/koek-rust.git"
exclude = [".vscode"]

[dependencies]
